#index:
#    path: /
#    controller: App\Controller\DefaultController::index

groups:
  path: /groups
  controller: App\Controller\HomeController::index

students:
  path: /students
  controller: App\Controller\HomeController::index