#index:
#    path: /
#    controller: App\Controller\DefaultController::index

groups:
  path: /groups
  controller: App\Controller\HomeController::index

students:
  path: /students
  controller: App\Controller\HomeController::index

students.create:
  path: /students/create
  controller: App\Controller\HomeController::index

students.edit:
  path: /students/edit/{id}
  controller: App\Controller\HomeController::index